# Generated by Django 4.0.1 on 2022-01-15 21:05

from django.db import migrations, models

from products.gen_master_data import gen_master


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='이름'),
        ),
        migrations.RunPython(gen_master),
    ]
